// translate/src/app/pages/about-us/about-us.component.ts
import { Component } from '@angular/core';
import { IonicModule } from '@ionic/angular';

@Component({
  selector: 'app-about-us',
  standalone: true,
  imports: [IonicModule], // Import IonicModule directly for standalone components
  templateUrl: './about-us.component.html',
  styleUrls: ['./about-us.component.scss']
})
export class AboutUsComponent {}

<ion-content [fullscreen]="true">
    <main class="about-container">
      <section class="about-section vision">
        <div class="text-box">
          <h3>Our Vision</h3>
          <p>
            Our vision is to provide a platform that enables individuals to bridge communication barriers across different languages, including sign languages. By focusing on English, German, and French, we aim to make sign language accessible and understandable for everyone, whether they are learning, teaching, or simply exploring new ways to communicate.
          </p>
        </div>
        <div class="image-box">
          <img src="/assets/images/D_NQ_NP_2X_658862-MPE71312099018_082023-F.webp" alt="Our Vision" />
        </div>
      </section>
  
      <section class="about-section mission">
        <div class="image-box">
          <img src="/assets/images/Signing-Image.webp" alt="Our Mission" />
        </div>
        <div class="text-box">
          <h3>Our Mission</h3>
          <p>
            Our mission is to simplify sign language translation, making it accessible for all users through the use of advanced technology. By supporting multiple languages and providing seamless translation options, we encourage more people to engage with sign languages, promote inclusivity, and foster a deeper understanding across communities.
          </p>
        </div>
      </section>
  
      <section class="about-section story">
        <div class="text-box">
          <h3>Our Story</h3>
          <p>
            Sign languages enrich our ability to communicate, yet accessing them has often been challenging. Our platform serves as a bridge, offering real-time, accurate translation between spoken languages and sign languages, specifically focusing on English, German, and French. Whether for educational purposes, personal interest, or cross-cultural interaction, we make sign language more accessible, promoting a more connected and inclusive world.
          </p>
        </div>
        <div class="image-box">
          <img src="/assets/images/image-19.png" alt="Our Story" />
        </div>
      </section>
    </main>
  </ion-content>

// front-end/src/app/aboutus/page.jsx
import React from "react";
import Link from "next/link";
import "./../../styles/aboutus.css";


export default function AboutPage() {
  return (
    

        <main className="about-container">
          <h1>About</h1>
          <h2>Web name</h2>


          <section className="about-section vision">
            <div className="text-box">
              <h3>Our Vision</h3>
              <p>
                Our vision is to provide a platform that empowers deaf individuals to communicate more effectively with their communities globally. By using modern subtitles and American Sign Language (ASL), we aim to create content seamlessly and help deaf content creators engage with their audience.
              </p>
            </div>
            <div className="image-box">
              <img
                src="/images/D_NQ_NP_2X_658862-MPE71312099018_082023-F.webp"
                alt="Our Vision"
              />
            </div>
          </section>

    
          <section className="about-section mission">
            <div className="image-box">
              <img
                src="/images/Signing-Image.webp"
                alt="Our Mission"
              />
            </div>
            <div className="text-box">
              <h3>Our Mission</h3>
              <p>
                Our mission is to empower deaf content creators by simplifying the subtitle creation process using advanced technology. Our platform enables more engagement with audiences, ensures content accessibility, and promotes inclusivity.
              </p>
            </div>
          </section>

          
          <section className="about-section story">
            <div className="text-box">
              <h3>Our Story</h3>
              <p>
                Social media empowers creators, but deaf individuals face challenges with accessible content. Our platform bridges the gap for deaf creators, automatically providing accurate and real-time subtitles, making the process faster and more efficient, and helping to support faster and more inclusive digital spaces.
              </p>
            </div>
            <div className="image-box">
              <img
                src="/images/image-19.png"
                alt="Our Story"
              />
            </div>
          </section>
        </main>
     
  );
}
